#!/bin/bash
#module load openmpi/gnu/1.6.5
./clean || exit
srcs="mytype.f90 data.f90 timestep.f90 sub.f90"
objs=`echo $srcs | sed 's/\.f90/.o/g'`
echo $srcs
echo $objs
for src in $srcs ; do
   mpif90 -c -fPIC -Wall -g $src     ||exit
done
mpif90 -o main main.f90 $objs || exit
f2py sub.f90 -m sub --overwrite-signature -h sub.pyf ||exit
f2py -c --fcompiler=gnu95 -m sub $objs sub.pyf -L/usr/lib/openmpi/lib -lmpi_f77 -lmpi -lgfortran||exit
mpiexec -n 4 ./main || exit
mpiexec -n 5 python a.py || exit
echo all done
